[project]
name = "advanced-finances"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "binance>=0.3.86",
    "bokeh>=3.8.1",
    "bs4>=0.0.2",
    "clickhouse-driver>=0.2.10",
    "cloudscraper>=1.2.71",
    "colorama>=0.4.6",
    "cryptography>=46.0.3",
    "dotenv>=0.9.9",
    "lxml>=6.0.2",
    "matplotlib>=3.10.7",
    "polars>=1.35.2",
    "pre-commit>=4.5.1",
    "python-binance>=1.0.32",
    "reportlab>=4.4.5",
    "requests>=2.32.5",
    "scikit-learn>=1.7.2",
    "ta>=0.11.0",
    "tqdm>=4.67.1",
]
